### ISSUE TITLE
Update the `nativescript-orientation` dependency to 2.0.1

### ISSUE THREAD

**Issue by alexandruantonica** [toddanglin/nativescript-trace-raven#4]
Hi @toddanglin,

Can you help us with an update of `nativescript-orientation` plugin to [2.0.1 ](https://github.com/NathanaelA/nativescript-orientation)? 

Thanks

**Comment by toddanglin** [comment]
Hey @alexandruantonica. Let me see if I can update that dependency this week. Sorry for the delay.

In the meantime, as a workaround, you can obviously update this dependency locally (after installing the plugin) OR for this plugin and reference your own version. (To that end, I'm also happy to merge a pull request if you want to update and test the new package. :))

**Comment by toddanglin** [comment]
Resolved with latest update (v1.1.1)
